import {
  SwedishScorecardModal,
  Par72ScorecardModal,
  PelzScorecardModal,
  ProximityScorecardModal,
  NegativeScorecardModal,
  JuniorPuttingScorecardModal,
  JuniorShortGameScorecardModal,
  SundayStandardScorecardModal,
  SwedishQuickFireScorecardModal,
  PelzSnapshotScorecardModal,
  BroadieChaseModal,
  PointsRaceScorecardModal,
  BroadieTestModal,
  LukeDonaldScorecardModal,
  GauntletScorecardModal,
  Challenge250ScorecardModal,
  SuddenDeathCarouselModal,
  SuddenDeathCarouselMiniModal,
  DrawbackGauntletModal,
  JaggedPeaksModal,
  AscentModal,
  AnchorModal,
  CrucibleModal,
  SniperSchoolModal,
  HoleAllDistancesModal,
  LieMixScorecardModal,
  TapToToggleModal,
  SpiralHoleOutModal,
  EliminatorModal,
  GateCompletionModal,
  NineHoleChippingModal,
  BankDrillModal,
  EnglandGolfPuttingModal,
} from './scorecards';

export const SCORECARD_MODALS = {
  1:   { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  2:   { component: Par72ScorecardModal,           icon: "⛳",  label: "" },
  3:   { component: NineHoleChippingModal,         icon: "🏌️", label: "pts" },
  8:   { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  9:   { component: PelzScorecardModal,            icon: "🏌️", label: "pts" },
  10:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  11:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  12:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  13:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  14:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  15:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  16:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  17:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  18:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  19:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  20:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  21:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  22:  { component: NegativeScorecardModal,        icon: "🤠",  label: "" },
  23:  { component: NegativeScorecardModal,        icon: "🤠",  label: "" },
  24:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  25:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  26:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  27:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  28:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  29:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  30:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  31:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  32:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  33:  { component: GauntletScorecardModal,        icon: "🎯",  label: "/ 18" },
  34:  { component: Challenge250ScorecardModal,    icon: "📏",  label: "ft" },
  35:  { component: SuddenDeathCarouselModal,      icon: "🎯",  label: "holed" },
  36:  { component: DrawbackGauntletModal,         icon: "🔄",  label: "putts" },
  37:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  42:  { component: SundayStandardScorecardModal,  icon: "📋",  label: "/ 48" },
  44:  { component: SpiralHoleOutModal,            icon: "🌀",  label: "/ 18" },
  45:  { component: JaggedPeaksModal,              icon: "⛰️",  label: "putts" },
  46:  { component: EliminatorModal,               icon: "🎯",  label: "putts" },
  47:  { component: EliminatorModal,               icon: "🎯",  label: "putts" },
  48:  { component: EliminatorModal,               icon: "🎯",  label: "putts" },
  49:  { component: LukeDonaldScorecardModal,       icon: "🎯",  label: "/ 20" },
  50:  { component: GateCompletionModal,           icon: "🚪",  label: "putts" },
  51:  { component: GateCompletionModal,           icon: "🚪",  label: "putts" },
  52:  { component: GateCompletionModal,           icon: "🚪",  label: "putts" },
  53:  { component: HoleAllDistancesModal,         icon: "🎯",  label: "putts" },
  54:  { component: HoleAllDistancesModal,         icon: "🎯",  label: "putts" },
  55:  { component: HoleAllDistancesModal,         icon: "🎯",  label: "putts" },
  56:  { component: HoleAllDistancesModal,         icon: "🎯",  label: "putts" },
  57:  { component: HoleAllDistancesModal,         icon: "🎯",  label: "putts" },
  58:  { component: HoleAllDistancesModal,         icon: "🎯",  label: "putts" },
  59:  { component: HoleAllDistancesModal,         icon: "🎯",  label: "putts" },
  60:  { component: TapToToggleModal,              icon: "🎯",  label: "holed" },
  61:  { component: TapToToggleModal,              icon: "🎯",  label: "holed" },
  62:  { component: TapToToggleModal,              icon: "🎯",  label: "holed" },
  63:  { component: AnchorModal,                   icon: "⚓",  label: "putts" },
  64:  { component: CrucibleModal,                 icon: "🔒",  label: "putts" },
  65:  { component: CrucibleModal,                 icon: "🚫",  label: "putts" },
  66:  { component: CrucibleModal,                 icon: "⚔️",  label: "putts" },
  67:  { component: SniperSchoolModal,             icon: "🎯",  label: "putts" },
  68:  { component: DrawbackGauntletModal,         icon: "🔄",  label: "putts" },
  69:  { component: PointsRaceScorecardModal,      icon: "🎯",  label: "putts" },
  70:  { component: BroadieChaseModal,             icon: "🏌️", label: "putts" },
  71:  { component: BroadieChaseModal,             icon: "🏌️", label: "putts" },
  72:  { component: BroadieChaseModal,             icon: "🏌️", label: "putts" },
  73:  { component: BroadieTestModal,              icon: "🏌️", label: "pts" },
  74:  { component: BroadieTestModal,              icon: "🏌️", label: "pts" },
  75:  { component: BroadieTestModal,              icon: "🏌️", label: "pts" },
  76:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  77:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  78:  { component: JuniorPuttingScorecardModal,   icon: "🟢",  label: "putts" },
  79:  { component: JuniorShortGameScorecardModal, icon: "🏌️", label: "pts" },
  80:  { component: LieMixScorecardModal,          icon: "⛱️",  label: "pts" },
  81:  { component: LieMixScorecardModal,          icon: "⛱️",  label: "pts" },
  82:  { component: LieMixScorecardModal,          icon: "⛱️",  label: "pts" },
  83:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  84:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  85:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  86:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  87:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  88:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  89:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  90:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  91:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  92:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  93:  { component: SwedishScorecardModal,         icon: "🇸🇪", label: "pts" },
  94:  { component: SwedishQuickFireScorecardModal, icon: "🇸🇪", label: "pts" },
  95:  { component: PelzSnapshotScorecardModal,    icon: "🏌️", label: "pts" },
  96:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  97:  { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  98:  { component: TapToToggleModal,              icon: "🎯",  label: "holed" },
  99:  { component: AscentModal,                   icon: "🧗",  label: "ft" },
  101: { component: BankDrillModal,                icon: "🏦",  label: "shots" },
  102: { component: BankDrillModal,                icon: "🏦",  label: "shots" },
  103: { component: GateCompletionModal,           icon: "🚪",  label: "putts" },
  104: { component: GateCompletionModal,           icon: "🚪",  label: "putts" },
  105: { component: ProximityScorecardModal,       icon: "📏",  label: "ft" },
  106: { component: SuddenDeathCarouselMiniModal,  icon: "🎯",  label: "holed" },
  107: { component: EnglandGolfPuttingModal,       icon: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", label: "putts" },
};

export const SCORECARD_DRILL_IDS = new Set(
  Object.keys(SCORECARD_MODALS).map(Number)
);
